export enum BooleansActionsType {
    PICKED_FAVORITE_LOCATION_FLAG_ON = "PICKED_FAVORITE_LOCATION_FLAG_ON",
    PICKED_FAVORITE_LOCATION_FLAG_OFF = "PICKED_FAVORITE_LOCATION_FLAG_OFF",
    SET_FAVORITE_LOCATION_ON = "SET_FAVORITE_LOCATION_ON",
    SET_FAVORITE_LOCATION_OFF = "SET_FAVORITE_LOCATION_OFF",
    FAVORITES_PAGE_ACTIVE = " FAVORITES_PAGE_ACTIVE",
    FAVORITES_PAGE_INACTIVE = " FAVORITES_PAGE_INACTIVE"

}