export enum CurrentLocationActionsType {
  GET_LOCATION_BY_GEOPOSITION_LOADING = "GET_LOCATION_BY_GEOPOSITION_LOADING",
  GET_LOCATION_BY_GEOPOSITION_SUCCESS = "GET_LOCATION_BY_GEOPOSITION_SUCCESS",
  GET_LOCATION_BY_GEOPOSITION_ERROR = "GET_LOCATION_BY_GEOPOSITION_ERROR",
  GET_GEOPOSITION_COORDINATES_ERROR = "GET_GEOPOSITION_COORDINATES_ERROR",
  SET_CURRNET_LOCATION = "SET_CURRNET_LOCATION",
}
