export enum CurrentConditionsActionType {
  GET_CURRENT_CONDITIONS_LOADING = "GET_CURRENT_CONDITIONS_LOADING",
  GET_CURRENT_CONDITIONS_SUCCESS = "GET_CURRENT_CONDITIONS_SUCCESS",
  GET_CURRENT_CONDITIONS_ERROR = "GET_CURRENT_CONDITIONS_ERROR",
}
