export enum DailyForecastsActionsType {
  GET_DAILY_FORECASTS_LOADING = "GET_DAILY_FORECASTS_LOADING ",
  GET_DAILY_FORECASTS_SUCCESS = "GET_DAILY_FORECASTS_SUCCESS ",
  GET_DAILY_FORECASTS_ERROR = "GET_DAILY_FORECASTS_ERROR",
}
