export enum FavoritesLocationActionsType {
  GET_FAVORITE_LOCATION_CONDITIONS_lOADING = "GET_FAVORITE_LOCATION_CONDITIONS_lOADING",
  GET_FAVORITE_LOCATION_CONDITIONS_SUCCESS = "GET_FAVORITE_LOCATION_CONDITIONS_SUCCESS",
  GET_FAVORITE_LOCATION_CONDITIONS_ERROR = "GET_FAVORITE_LOCATION_CONDITIONS_ERROR",
}
