export enum LocationsActionsType {
  GET_LOCATIONS_LOADING = "GET_LOCATIONS_LOADING",
  GET_LOCATIONS_SUCCESS = "GET_LOCATIONS_SUCCESS",
  GET_LOCATIONS_ERROR = "GET_LOCATIONS_ERROR",
  INIT_LOCATIONS_STATE_DATA = "INIT_LOCATIONS_STATE_DATA",
  INIT_LOCATIONS_STATE_ERROR = "INIT_LOCATIONS_STATE_ERROR",
}
